# Schema for the configuration files of the mailchimp_signup module.

mailchimp_signup.mailchimp_signup.*:
  type: config_entity
  label: 'Mailchimp Signup config'
  mapping:
    id:
      type: string
      label: 'Machine Name'
    title:
      type: text
      label: 'Title'
    uuid:
      type: string
      label: 'UUID'
    mc_lists:
      type: sequence
      label: 'Mailchimp List(s)'
    mode:
      type: int
      label: 'Mode'
    mergefields:
      type: sequence
      label: 'Mergefields'
    description:
      type: text
      label: 'Description'
    doublein:
      type: boolean
      label: 'Double-Opt-In'
    send_welcome:
      type: boolean
      label: 'Send Welcome'
    include_interest_groups:
      type: boolean
      label: 'Include Interest Groups'
    status:
      type: boolean
      label: 'Status'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        path:
          type: string
          label: 'Path'
        submit_button:
          type: text
          label: 'Submit Button'
        confirmation_message:
          type: text
          label: 'Confirmation Message'
        destination:
          type: string
          label: 'Destination'
